flask-getting-started-master/app/models.py
from . import db, login_manager
from flask_login import UserMixin, AnonymousUserMixin
from datetime import datetime
from markdown import markdown


class Role(db.Model):
    __tablename__ = 'roles'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    users = db.relationship('User', backref='role')

    @staticmethod
    def seed():
        db.session.add_all(map(lambda r: Role(name=r), ['Guests', 'Administrators']))
        db.session.commit()


class User(UserMixin, db.Model):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String)
    email = db.Column(db.String)
    password = db.Column(db.String)
    role_id = db.Column(db.Integer, db.ForeignKey('roles.id'))

    posts = db.relationship('Post', backref='author')
    comments = db.relationship('Comment', backref='author')

    locale = db.Column(db.String, default='zh')

    @staticmethod
    def on_created(target, value, oldvalue, initiator):
        target.role = Role.query.filter_by(name='Guests').first()


class AnonymousUser(AnonymousUserMixin):
    @property
    def locale(self):
        return 'zh'

    def is_administrator(self):
        return False


login_manager.anonymous_user = AnonymousUser


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


db.event.listen(User.name, 'set', User.on_created)


class Post(db.Model):
    __tablename__ = 'posts'
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String)
    body = db.Column(db.String)
    body_html = db.Column(db.String)
    created = db.Column(db.DateTime, index=True, default=datetime.utcnow)

    comments = db.relationship('Comment', backref='post')
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    @staticmethod
    def on_body_changed(target, value, oldvalue, initiator):
        if value is None or (value is ''):
            target.body_html = ''
        else:
            target.body_html = markdown(value)


db.event.listen(Post.body, 'set', Post.on_body_changed)


class Comment(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    body = db.Column(db.String)
    created = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    author_id = db.Column(db.Integer, db.ForeignKey('users.id'))

flask-getting-started-master/app/main/forms.py
# coding=utf-8

from flask.ext.wtf import Form
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired
from flask.ext.pagedown.fields import PageDownField
from flask_babel import gettext as _


class PostForm(Form):
    title = StringField(label=_(u"标题"), validators=[DataRequired()])
    body = PageDownField(label=_(u"正文"), validators=[DataRequired()])
    submit = SubmitField(_(u"发表"))


class CommentForm(Form):
    body = PageDownField(label=_(u'评论'), validators=[DataRequired()])
    submit = SubmitField(_(u'发表'))

flask-getting-started-master/app/__init__.py
# coding: utf-8

from flask import Flask, request
from os import path
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager, current_user
from flask_pagedown import PageDown
from flask_gravatar import Gravatar
from flask_babel import Babel, gettext as _
from config import config

basedir = path.abspath(path.dirname(__file__))

db = SQLAlchemy()
babel = Babel()
bootstrap = Bootstrap()
pagedown = PageDown()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'


def create_app(config_name='default'):
    app = Flask(__name__)
    app.config.from_object(config[config_name])


    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    pagedown.init_app(app)

    babel.init_app(app)
    Gravatar(app, size=64)

    from auth import auth as auth_blueprint
    from main import main as main_blueprint

    app.register_blueprint(auth_blueprint, url_prefix='/auth')
    app.register_blueprint(main_blueprint, static_folder='static')

    @app.template_test('current_link')
    def is_current_link(link):
        return link == request.path

    @babel.localeselector
    def get_locale():
        return current_user.locale

    return app

# @app.route('/upload', methods=['GET', 'POST'])
# def upload():
#     if request.method == 'POST':
#         f = request.files['file']
#         basepath = path.abspath(path.dirname(__file__))
#         upload_path = path.join(basepath, 'static/uploads')
#         f.save(upload_path + '/' + secure_filename(f.filename))
#         return redirect(url_for('upload'))
#     return render_template('upload.html')

flask-getting-started-master/app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

import views

flask-getting-started-master/app/main/views.py
# -*- coding: utf-8 -*-

from flask import render_template, request, flash, redirect, url_for,current_app,abort
from . import main
from .. import db
from ..models import Post, Comment
from flask.ext.login import login_required, current_user
from .forms import CommentForm, PostForm
from flask_babel import gettext as _


@main.errorhandler(404)
def page_not_found(error):
    return render_template('404.html'), 404


@main.route('/')
def index():
    # posts=Post.query.all()

    page_index = request.args.get('page', 1, type=int)

    query = Post.query.order_by(Post.created.desc())

    pagination = query.paginate(page_index, per_page=20, error_out=False)

    posts = pagination.items

    return render_template('index.html',
                           title=_(u'欢迎来到Ray的博客'),
                           posts=posts,
                           pagination=pagination)


@main.route('/about')
def about():
    return render_template('about.html', title=u'关于')


@main.route('/posts/<int:id>', methods=['GET', 'POST'])
def post(id):
    # Detail 详情页
    post = Post.query.get_or_404(id)

    # 评论窗体
    form = CommentForm()

    # 保存评论
    if form.validate_on_submit():
        comment = Comment(author=current_user,
                          body=form.body.data,
                          post=post)
        db.session.add(comment)
        db.session.commit()

    return render_template('posts/detail.html',
                           title=post.title,
                           form=form,
                           post=post)


@main.route('/edit', methods=['GET', 'POST'])
@main.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id=0):
    form = PostForm()

    if id == 0:
        post = Post(author=current_user)
    else:
        post = Post.query.get_or_404(id)

    if form.validate_on_submit():
        post.body = form.body.data
        post.title = form.title.data

        db.session.add(post)
        db.session.commit()

        return redirect(url_for('.post', id=post.id))

    form.title.data = post.title
    form.body.data = post.body

    title = _(u'添加新文章')
    if id > 0:
        title = _(u'编辑 - %(title)', title=post.title)

    return render_template('posts/edit.html',
                           title=title,
                           form=form,
                           post=post)

@main.route('/shoutdown')
def shutdown():
    if not current_app.testing:
        abort(404)

    shoutdown = request.environ.get('werkzeug.server.shutdown')
    if not shoutdown:
        abort(500)

    shoutdown()
    return u'正在关闭服务端进程...'

flask-getting-started-master/doc/app.py
# -*- code:utf-8 -*-
from flask import Flask, render_template
from livereload import Server

app = Flask(__name__)


@app.route('/')
def index():
    return render_template('index.html',
                           title="<h1>Hello world</h1>",
                           body="## Header2")

@app.template_filter('md')
def markdown_to_html(txt):
    from markdown import markdown
    return markdown(txt)

def read_md(filename):
    with open(filename) as md_file:
        content = reduce(lambda x, y: x + y, md_file.readlines())
    return content.decode('utf-8')



@app.context_processor
def inject_methods():
    return dict(read_md=read_md)

if __name__ == '__main__':
    live_server = Server(app.wsgi_app)
    live_server.watch('**/*.*')
    live_server.serve(open_url=True)

flask-getting-started-master/app/templates/_index.html
{% extends 'base.html' %}
{% import '_marcos.html' as ui %}

{% block title %}{{ title }}{% endblock %}
{% block content %}
    {% set links=[
    ('Home', url_for('.index')),
    ('About',url_for('.about')),
    ('Services', url_for('.services')),
    ('Projects',url_for('.projects')),
] %}

    <nav>
        {% for label,href in links %}
            {% if not loop.first %} | {% endif %}
            <a href="{% if href is current_link %} #
            {% else %}
            {{ href }}
            {% endif %}">
                {{ label }}</a>
        {% endfor %}
    </nav>
    <h1>{{ self.title() }}</h1>

    {{ ui.input('username') }}
    {{ ui.input('password',type='password') }}

{% endblock content %}

{% block footer %}
    <hr>
    {{ super() }}
{% endblock %}

flask-getting-started-master/app/templates/_marcos.html
{% macro input(name,value='',type='text',size=20) %}
    <input type="{{ type }}"
           name="{{ name }}"
           value="{{ value }}"
           size="{{ size }}"
            />
{% endmacro %}

flask-getting-started-master/app/templates/about.html
{% extends 'base.html' %}
{% block page_body %}
    <div class="container">
    </div>
{% endblock %}

flask-getting-started-master/app/templates/base.html
{% extends 'bootstrap/base.html' %}
{% block title %}{{ title }}{% endblock %}
{% block head %}
    {{ super() }}
    {% include ['includes/_head.html', 'includes/_metas.html'] %}
{% endblock %}
{% block styles %}
    {{ super() }}
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/cerulean/bootstrap.min.css">
{% endblock %}
{% block navbar %}
    {# { nav.top.render() }} #}
    {% include 'includes/_navbar.html' %}
{% endblock %}

{% block content %}
    {% block header %}
        <header>
            <div class="page-header">
                <div class="container">
                    <h1>{{ title }}</h1>
                </div>
            </div>
        </header>
    {% endblock %}
    {% block page_body %}
    {% endblock %}
{% endblock %}
{% block footer %}
    <footer>
        Copyright 2015 by <a href="ray.dotnetage.com">Ray</a>
    </footer>
{% endblock %}

flask-getting-started-master/app/templates/includes/_head.html
<meta charset="UTF-8">
<link href="{{ url_for('static',filename='site.css') }}" rel="stylesheet">
<title>{% block title %}{% endblock %}</title>

flask-getting-started-master/app/templates/includes/_navbar.html
<nav class="navbar navbar-default navbar-static-top">
    <div class="container-fluid">
        <div class="navbar-header">
            <button aria-controls="navbar"
                    aria-expanded="false"
                    class="navbar-toggle collapsed"
                    data-target="#7bc75dbef69e41ff2452de70079c8ece1320ea7c"
                    data-toggle="collapse" type="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <span class="navbar-brand">Flask入门</span>
        </div>
        <div class="navbar-collapse collapse"
             id="7bc75dbef69e41ff2452de70079c8ece1320ea7c">
            <ul class="nav navbar-nav">
                <li {% if url_for('main.index') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.index') }}" title="{{ _("主页") }}">{{ _("主页") }}</a>
                </li>
                <li {% if url_for('main.about') is current_link %}class="active"{% endif %}>
                    <a href="{{ url_for('main.about') }}" title="{{ _("关于") }}">{{ _("关于") }}</a>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if current_user.is_authenticated() %}
                    <li><a href="#">{{ current_user.name }}</a></li>
                    <li><a href="{{ url_for('auth.logout') }}">{{ _("退出") }}</a></li>
                {% else %}
                    <li><a href="{{ url_for('auth.login') }}">{{ _("登录") }}</a></li>
                    <li><a href="{{ url_for('auth.register') }}">{{ _("注册") }}</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

flask-getting-started-master/app/templates/index.html
{% extends 'base.html' %}
{% from "bootstrap/pagination.html" import render_pagination %}

{% block page_body %}
    <div class="container">
        <a href="{{ url_for('main.edit') }}" class="btn btn-primary">发表新文章</a>
    </div>
    <div class="container">
        {% for post in posts %}
            <h2><a href="{{ url_for('main.post', id = post.id) }}">{{ post.title }}</a></h2>
            <div>
                {{ post.body_html|safe }}
            </div>
        {% endfor %}

        {% if pagination %}
            {{ render_pagination(pagination) }}
        {% endif %}

    </div>
{% endblock %}

flask-getting-started-master/app/templates/login.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block page_body %}
    <div class="container">
        {% for message in get_flashed_messages() %}
           <div class="alert-info"> {{ message }}</div>
        {% endfor %}
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

flask-getting-started-master/app/templates/posts/detail.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_body %}
    <div class="container">
        {# Meta 信息 #}
        <span>作者:{{ post.author.name }}</span> <span>{{ _("发表日期") }}:{{ post.created }}</span>

        {# 正文 #}
        <div>
            {{ post.body_html | safe }}
        </div>

        {# 操作链接 #}
        <h3>评论</h3>
        {# 发表评论 #}
        <div>
            {{ wtf.quick_form(form) }}
        </div>

        {# 评论列表 #}
        {% for comment in post.comments|sort(attribute='created',reverse=True ) %}
            <div class="media">
                <div class="media-left">
                    <a href="#">
                        <img class="media-object img-circle" src="{{ comment.author.email | gravatar }}">
                    </a>
                </div>
                <div class="media-body">
                    <small class="text-muted">{{ comment.created }}</small>
                    <div>{{ comment.body }}</div>

                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

flask-getting-started-master/app/templates/posts/edit.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block scripts %}
    {{ super() }}
    {{ pagedown.include_pagedown() }}
{% endblock %}

{% block page_body %}
    <div class="container">
        <form method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.title(class="form-control", placeholder=_("请输入文章标题")  ) }}
            </div>
            <div class="form-group">
                {{ form.body(only_input=True,rows=10,class="form-control") }}
            </div>
            <div>
                {{ form.body(only_preview=True) }}
            </div>
            <div class="form-group">
                {{ form.submit(class="btn btn-primary") }}
            </div>

        </form>
    </div>
{% endblock %}

flask-getting-started-master/app/templates/register.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}
{% block page_body %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert-info"> {{ message }}</div>
        {% endfor %}
        {{ wtf.quick_form(form) }}
    </div>
{% endblock %}

flask-getting-started-master/app/templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Upload new File</title>

</head>
<body>

<h1>文件上传示例</h1>

<form action=""
      method=post
      enctype=multipart/form-data>
    <p><input type=file name=file>
        <input type=submit value=Upload></p>
</form>
</body>
</html>